_wandb:
    value:
        cli_version: 0.21.2
        e:
            s2dfv568u2iykfbvoqoxk56nya5f1bqu:
                codePath: Policy_Learning\gpu_limbic.py
                codePathLocal: Policy_Learning\gpu_limbic.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "510744588288"
                        used: "462909394944"
                email: mehul22@iisertvm.ac.in
                executable: C:\Users\mehul\anaconda3\envs\clean\python.exe
                git:
                    commit: 658094fe722a721bb2cbe6d076f6d97b7060e6df
                    remote: https://github.com/Mehul1729/RL-for-IGT.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-96ef0870-1a5f-024b-b3dd-89750af5ad91
                host: LAPTOP-EIU04378
                memory:
                    total: "16870006784"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\mehul\RL-for-IGT\Policy_Learning\gpu_limbic.py
                python: CPython 3.11.11
                root: C:\Users\mehul\RL-for-IGT
                startedAt: "2025-12-23T10:15:36.063841Z"
                writerId: s2dfv568u2iykfbvoqoxk56nya5f1bqu
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.11.11
            "5": 0.21.2
            "8":
                - 3
            "12": 0.21.2
            "13": windows-amd64
architecture:
    value: SimpleMLP_32
environment:
    value: Extreme-8-Deck
episodes:
    value: 3000
gamma:
    value: 0.3
learning_rate:
    value: 0.005
n_actions:
    value: 8
