_wandb:
    value:
        cli_version: 0.21.2
        e:
            m2ynoj43djlfoaora2i8w4sawjshulec:
                codePath: RL-Agent-for_IGT\agent2.py
                codePathLocal: agent2.py
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "510744588288"
                        used: "496563236864"
                email: mehul22@iisertvm.ac.in
                executable: C:\Users\mehul\anaconda3\envs\clean\python.exe
                git:
                    commit: 1efdca42d19ce0725e8f7ca120660d8e8a84550f
                    remote: https://github.com/Mehul1729/RL-for-IGT
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-96ef0870-1a5f-024b-b3dd-89750af5ad91
                host: LAPTOP-EIU04378
                memory:
                    total: "16870006784"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\mehul\RL-for-IGT\RL-Agent-for_IGT\agent2.py
                python: CPython 3.11.11
                root: C:\Users\mehul\RL-for-IGT\RL-Agent-for_IGT
                startedAt: "2026-02-18T14:10:21.622616Z"
                writerId: m2ynoj43djlfoaora2i8w4sawjshulec
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
            "4": 3.11.11
            "5": 0.21.2
            "8":
                - 3
            "12": 0.21.2
            "13": windows-amd64
architecture:
    value: SimpleMLP_32
environment:
    value: Extreme-8-Deck
episodes:
    value: 1000
gamma:
    value: 0.3
learning_rate:
    value: 0.005
n_actions:
    value: 8
